
package weshampson.timekeeper.gui;

import java.util.Date;
import java.util.List;
import weshampson.timekeeper.signout.Signout;
import weshampson.timekeeper.signout.SignoutManager;
import weshampson.timekeeper.tech.Tech;

/**
 *
 * @author  Wes Hampson
 * @version 0.3.0 (Nov 15, 2014)
 * @since   0.3.0 (Nov 15, 2014)
 */
public class TechInfoDialog extends javax.swing.JDialog {

    /** Creates new form TechInfoDialog */
    public TechInfoDialog(java.awt.Frame parent, boolean modal, Tech t) {
        super(parent, modal);
        initComponents();
        techInfoIDNumber.setText(Integer.toString(t.getID()));
        techInfoName.setText(t.getName());
        techInfoCreationDate.setText(t.getCreationDate().toString());
        techInfoLastLogin.setText(t.getLastLoginDate() == null ? "Never logged in" : t.getLastLoginDate().toString());
        techInfoLastSignout.setText(t.getLastSignoutDate() == null ? "Never signed out" : t.getLastSignoutDate().toString());
        techInfoCurrentlyLoggedIn.setText(Boolean.toString(t.isLoggedIn()));
        techInfoCurrentlySignedOut.setText(Boolean.toString(t.isSignedOut()));
        techInfoLoginCount.setText(Integer.toString(t.getLoginCount()));
        techInfoSignoutCount.setText(Integer.toString(t.getSignoutCount()));
        List<Signout> techSignouts = SignoutManager.getSignoutsByTechID(t.getID());
        if (!techSignouts.isEmpty()) {
            Date nextSignoutDate = techSignouts.get(0).getScheduledSignoutDate();
            for (Signout s : techSignouts) {
                Date d = s.getScheduledSignoutDate();
                if (d.compareTo(nextSignoutDate) < 0) {
                    nextSignoutDate = d;
                }
            }
            techInfoNextSignout.setText(nextSignoutDate.toString());
        } else {
            techInfoNextSignout.setText("No scheduled signouts");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        techInfoIDNumberTitle = new javax.swing.JLabel();
        techInfoIDNumber = new javax.swing.JLabel();
        techInfoNameTitle = new javax.swing.JLabel();
        techInfoName = new javax.swing.JLabel();
        techInfoCreationDateTitle = new javax.swing.JLabel();
        techInfoCreationDate = new javax.swing.JLabel();
        techInfoLastLoginTitle = new javax.swing.JLabel();
        techInfoLastLogin = new javax.swing.JLabel();
        techInfoLastSignoutTitle = new javax.swing.JLabel();
        techInfoLastSignout = new javax.swing.JLabel();
        techInfoNextSignoutTitle = new javax.swing.JLabel();
        techInfoNextSignout = new javax.swing.JLabel();
        techInfoCurrentlyLoggedInTitle = new javax.swing.JLabel();
        techInfoCurrentlyLoggedIn = new javax.swing.JLabel();
        techInfoCurrentlySignedOutTitle = new javax.swing.JLabel();
        techInfoCurrentlySignedOut = new javax.swing.JLabel();
        techInfoLoginCountTitle = new javax.swing.JLabel();
        techInfoLoginCount = new javax.swing.JLabel();
        techInfoSignoutCountTitle = new javax.swing.JLabel();
        techInfoSignoutCount = new javax.swing.JLabel();
        techInfoCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tech Info");

        techInfoIDNumberTitle.setText("ID number:");

        techInfoIDNumber.setText("<int>");

        techInfoNameTitle.setText("Name:");

        techInfoName.setText("<String>");

        techInfoCreationDateTitle.setText("Creation date:");

        techInfoCreationDate.setText("<Date>");

        techInfoLastLoginTitle.setText("Last Log in:");

        techInfoLastLogin.setText("<Date>");

        techInfoLastSignoutTitle.setText("Last sign out:");

        techInfoLastSignout.setText("<Date>");

        techInfoNextSignoutTitle.setText("Next sign out:");

        techInfoNextSignout.setText("<Date>");

        techInfoCurrentlyLoggedInTitle.setText("Currently logged in:");

        techInfoCurrentlyLoggedIn.setText("<boolean>");

        techInfoCurrentlySignedOutTitle.setText("Currently signed out:");

        techInfoCurrentlySignedOut.setText("<boolean>");

        techInfoLoginCountTitle.setText("Log in count:");

        techInfoLoginCount.setText("<int>");

        techInfoSignoutCountTitle.setText("Sign out count:");

        techInfoSignoutCount.setText("<int>");

        techInfoCloseButton.setText("Close");
        techInfoCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techInfoCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(techInfoCloseButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(techInfoSignoutCountTitle)
                    .addComponent(techInfoLoginCountTitle)
                    .addComponent(techInfoNameTitle)
                    .addComponent(techInfoIDNumberTitle)
                    .addComponent(techInfoLastLoginTitle)
                    .addComponent(techInfoLastSignoutTitle)
                    .addComponent(techInfoNextSignoutTitle)
                    .addComponent(techInfoCurrentlyLoggedInTitle)
                    .addComponent(techInfoCurrentlySignedOutTitle)
                    .addComponent(techInfoCreationDateTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(techInfoIDNumber)
                    .addComponent(techInfoName)
                    .addComponent(techInfoCreationDate)
                    .addComponent(techInfoNextSignout)
                    .addComponent(techInfoCurrentlyLoggedIn)
                    .addComponent(techInfoCurrentlySignedOut)
                    .addComponent(techInfoLastLogin)
                    .addComponent(techInfoLastSignout)
                    .addComponent(techInfoLoginCount)
                    .addComponent(techInfoSignoutCount))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoIDNumberTitle)
                    .addComponent(techInfoIDNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoNameTitle)
                    .addComponent(techInfoName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoCreationDate)
                    .addComponent(techInfoCreationDateTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoLastLoginTitle)
                    .addComponent(techInfoLastLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoLastSignoutTitle)
                    .addComponent(techInfoLastSignout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoNextSignoutTitle)
                    .addComponent(techInfoNextSignout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoCurrentlyLoggedInTitle)
                    .addComponent(techInfoCurrentlyLoggedIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoCurrentlySignedOutTitle)
                    .addComponent(techInfoCurrentlySignedOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoLoginCountTitle)
                    .addComponent(techInfoLoginCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(techInfoSignoutCountTitle)
                    .addComponent(techInfoSignoutCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(techInfoCloseButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void techInfoCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techInfoCloseButtonActionPerformed
        dispose();
    }//GEN-LAST:event_techInfoCloseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton techInfoCloseButton;
    private javax.swing.JLabel techInfoCreationDate;
    private javax.swing.JLabel techInfoCreationDateTitle;
    private javax.swing.JLabel techInfoCurrentlyLoggedIn;
    private javax.swing.JLabel techInfoCurrentlyLoggedInTitle;
    private javax.swing.JLabel techInfoCurrentlySignedOut;
    private javax.swing.JLabel techInfoCurrentlySignedOutTitle;
    private javax.swing.JLabel techInfoIDNumber;
    private javax.swing.JLabel techInfoIDNumberTitle;
    private javax.swing.JLabel techInfoLastLogin;
    private javax.swing.JLabel techInfoLastLoginTitle;
    private javax.swing.JLabel techInfoLastSignout;
    private javax.swing.JLabel techInfoLastSignoutTitle;
    private javax.swing.JLabel techInfoLoginCount;
    private javax.swing.JLabel techInfoLoginCountTitle;
    private javax.swing.JLabel techInfoName;
    private javax.swing.JLabel techInfoNameTitle;
    private javax.swing.JLabel techInfoNextSignout;
    private javax.swing.JLabel techInfoNextSignoutTitle;
    private javax.swing.JLabel techInfoSignoutCount;
    private javax.swing.JLabel techInfoSignoutCountTitle;
    // End of variables declaration//GEN-END:variables

}
